modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="modrpg"
version="1.0.0"
displayName="ModRpg"
authors="Juan"
description='''Mod de RPG con arbol de habilidades.'''

[[dependencies.modrpg]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.modrpg]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"